# Site settings
title: Blog
subtitle: zwstart
keywords: zwstart
description: this is program note of zwstart
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://zwstart.gitee.io/" # 你的域名
page_no_title: "zwstart's blog" # 文章无标题时默认显示内容
beian: # "备案号"
author: zwstart
email: 1183394882@qq.com

# Build settings
permalink: /:year/:month/:day/:title/
exclude: ["README.md", "changelog.md", "server", "tools", "Pipfile"]
plugins:
  - jekyll-paginate
  - jemoji


# always get github's error email saying redcarpet is not supported,
# so change it to kramdown.
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM


# Pageinate settings
paginate: 8 # 分页大小
paginate_path: "page/:num/"

# Search settings
baidu_search: true
google_search: # true

# Menu settings
menu:
  - page: 首页
    directory: .
    icon: icon-home
  - page: 归档
    directory: archives/
    icon: icon-archive
  - page: 标签
    directory: tags/
    icon: icon-tags
  - page: 留言
    directory: guestbook/
    icon: icon-guestbook
  - page: 关于
    directory: about/
    icon: icon-about
#  - page: 订阅
#    directory: feed.xml
#    icon: icon-rss

# Link settings
links: # 友情链接

  - title: zwstart's blog
    url: http://zwstart.gitee.io/


# Google Analytics
# ga_track_id: 'UA-130856615-1'            # Format: UA-xxxxxx-xx
# ga_domain: www.oukohou.wang              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto


# Code hub settings
codehub: # 代码仓库
  - title: Gitee
    url: https://gitee.com/zwstart


# valine:
#   enable: true
#   app_id:  K1rbn2Oo0YMM04VuzdLS7Nzz-gzGzoHsz
#   app_key: AAsHbwVm8ofKFJ6ghGqqrXSU
#   notify: false # mail notifier , https://github.com/xCss/Valine/wiki
#   verify: false # Verification code
#   visitor: true
#   avatar: retro
#   placeholder: say something~~\n - 昵称 为你所要显示的评论的ID；\n - 邮箱 只有后台可见，仅供讨论过程中是否需要交流邮件而设置，请放心填写;\n - 网址 为你的评论的昵称的超链接。\n当然，以上都可以不写，评论依然会显示……
#   guest_info: nick,mail,link
#   pageSize: 10
